### ISSUE TITLE
ransomware LOL

### ISSUE THREAD

**Issue by madeline-xoxo** [FeminineFemale/Fortnite-Unban-Pack#1]

**Comment by therealforger** [comment]
I think your just board, there is no ransomware. This program erases and rewrites many sensitive parts of your computer like hardware IDs so fortnite can't track you. That is the whole point of the program, so If you ran it through an antivirus and it said it was a ransomware then it was a false flag.

**Comment by therealforger** [comment]
Other than that, where is the "ransomware"?

**Comment by FeminineFemale** [comment]
If you think its ransomeware all the .exe file sources are in the description and the rest are from decompiling 1button with bat-to-exe converters exe-to-bat feature
